### ISSUE TITLE
Always "Not found" when using a search router

### ISSUE THREAD

**Issue by epodivilov** [nanostores/router#16]
Hi.

I discovered the problem, but wanted to clear the air first.
I found the problem in the router in search mode. I tried it in conjunction with SolidJS, but I always got the fallback "page not found".

I prepared an example in React that also reproduces this problem:
https://codesandbox.io/s/dank-frog-posp9v?file=/src/App.js

I have studied the code a bit and it seems that the problem is in [this line](https://github.com/nanostores/router/blob/main/index.js#L32). The problem is that in search mode, the parse function corrects the path `/p/?page=about` and turns it into `/ppage=about`. But the router stores RegExp `^\/p\/\?page\=about$` for the about page and the changed path is not matched by this RegExp in any way.

As far as I understand, the correction in the parse function is needed to normalize routes and remove the end slashes and `?`. For example, `/page/` turns into `/page`. But it seems that this correction either does not need to be done in search mode, or it can be done separately without affecting query parameters. For example, turn `/page/?param=1` into `/page?param=1`.

**Comment by ai** [comment]
Hi. Thanks for late response. Had tasks in another open source projects.

Yes, your research is right. I fixed the bug 788dcc3

**Comment by ai** [comment]
The fix was released in 0.8.3.

**Comment by jilio** [comment]
Hi there,

I experience the same issue on the newest router version (v0.11.0):
https://codesandbox.io/s/unruffled-stallman-r5c38f?file=/src/App.js

**Comment by jilio** [comment]
@epodivilov Yes, I tried.
I've updated the sample to the latest nanostores (v.0.9.3) an still no luck
https://codesandbox.io/s/unruffled-stallman-r5c38f?file=/src/App.js
